### PR TITLE
Jooby 1.1.0

### PR DESCRIPTION
**Pull request by jknack**
* update integration tests
* plus cool banner

### CODE REVIEW

**Comment by jknack** [comment]
@stevehu Here is an update to latest Jooby :)

What do you think of adding a comment when the test run in the IO vs Worker thread?

Jooby for example doesn't allow to run any code in IO thread.

**Comment by stevehu** [comment]
I think most new frameworks won't allow to run business logic in IO thread and this is what non-blocking is about. I think only servlet contain these days are using one thread for the request/response chain.

**Comment by jknack** [comment]
I'm probably reading it wrong, but [this code](https://github.com/networknt/microservices-framework-benchmark/blob/master/light-java/src/main/java/Example.java) run in the IO thread, no?

**Comment by stevehu** [comment]
I got the result published and it is a big improvement compare with the previous version. what has been changed? Yes. My code is using IO thread as for this test it is not necessary to start another thread. For database or other IO access, it will be changed to worker thread.

**Comment by jknack** [comment]
Somewhere in the path I introduced a performance regression. The 404 handler was creating a lot of garbage per each new request. This wasn't need it (of course), it was just a really silly mistake.

After I fixed that did some minor/micro improvements.

Regarding to the IO thread. Yes, I know we could run this test in the IO thread... just saying we should probably mention it. Running code in the IO thread will always give us better results (of course)

**Comment by stevehu** [comment]
Are you still using servlet container?

**Comment by jknack** [comment]
Never used a Servlet Container :)

Jooby comes with 3 server implementations Netty, Undertow and Jetty.

Jetty is a servlet container, but I tried to use plain/raw Jetty API as much as possible.

**Comment by stevehu** [comment]
Cool. Then you have a lot of room to go.

**Pull request merged**
