### PR TITLE
Update actframework benchmark program

### PR DESCRIPTION
**Pull request by greenlaw110**
**CHANGES**
* application now listening on port `8080`
* CLI service is disabled
* update to act-0.4.0-SNAPSHOT
* rename package and class 
* added `/json` endpoint for JSON serialization benchmark
* update README.md file
* add .gitignore to project

### CODE REVIEW

**Comment by stevehu** [comment]
The result looks pretty good!!! Thanks.

**Comment by greenlaw110** [comment]
Yep! And there are substantial optimization on Act-0.4.0, which is really triggered by running your benchmark project! Thank you very much!

**Comment by stevehu** [comment]
You still have potential:)

**Comment by greenlaw110** [comment]
Yeah but I think the performance exercise will be parked for now. My focus on Act is the developer experience, i.e. make it really easy to use. And it shall write fewer lines in comparing with other frameworks, of course the readability must not be sacrificed

**Pull request merged**
