### PR TITLE
Added ASP.NET Core Hello World

### PR DESCRIPTION
**Pull request by JesHansen**
A simple .NET Core (ASP.NET Core) project has been added.

### CODE REVIEW

**Comment by stevehu** [comment]
@JesHansen Do I need Windows to compile and start the server?

**Comment by JesHansen** [comment]
No. .NET Core is cross platform. You can get the runtime for Linux, Mac and Windows here: https://www.microsoft.com/net/download/core

**Comment by stevehu** [comment]
Thanks @JesHansen for the link. I will install it on my desktop to test it. I am very interested in the result and I think it is a good move for Microsoft as Linux is the most popular server platform now.

**Comment by JesHansen** [comment]
Agreed @stevehu. Even on their own cloud platform, a large percentage of the deployed VMs are running Linux. http://www.cio.com/article/3087875/cloud-computing/one-third-of-azure-virtual-machines-now-run-linux.html

**Comment by stevehu** [comment]
Result is published. Impressive!!! Thanks a lot for your help.

**Pull request merged**
