### PR TITLE
update act to 1.6.4, update jfinal to 3.3

### PR DESCRIPTION
**Pull request by greenlaw110**

### CODE REVIEW

**Comment by stevehu** [comment]
Thanks @greenlaw110 for your help.

**Comment by greenlaw110** [comment]
@stevehu thanks for accepting the PR. BTW do you plan to rerun the upgraded test project?

**Comment by stevehu** [comment]
I have rerun the test on the same computer but the result is slower than the previous one. I have upgraded my desktop to 17.10 and applied meltdown patch recently and I guess it is the root cause. I will leave the previous result there for now until the time I can rerun all tests.

**Comment by greenlaw110** [comment]
Thanks @stevehu

**Pull request merged**
